import { createDefaultUpscalerConfig } from '../../../../shared/formats';
import type {
  BatchImageUpscaleJob,
  BatchSequenceToVideoJob,
  BatchVideoToSequenceJob,
  BatchVideoUpscaleJob,
  ImageUpscaleJob,
  SequenceToVideoJob,
  VideoUpscaleJob,
  VideoToSequenceJob,
} from '../../../../shared/jobs';
import type { WorkflowCategory } from './types';

export const modeMeta: Array<{
  id: WorkflowCategory;
  title: string;
}> = [
  {
    id: 'Single',
    title: 'Single',
  },
  {
    id: 'Batch',
    title: 'Batch',
  },
];

export const initialSequenceToVideo: SequenceToVideoJob = {
  kind: 'sequence-to-video',
  sourceMode: 'folder',
  sequenceFolder: '',
  imagePaths: [],
  outputPath: '',
  fps: 24,
  speed: 1,
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: 'off',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realesrgan'),
  format: 'mp4-h264',
};

export const initialVideoToSequence: VideoToSequenceJob = {
  kind: 'video-to-sequence',
  videoPath: '',
  outputDir: '',
  fps: 24,
  speed: 1,
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: 'off',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realesrgan'),
  format: 'png',
  prefix: 'frame',
  startNumber: 1,
};

export const initialImageUpscale: ImageUpscaleJob = {
  kind: 'image-upscale',
  imagePaths: [],
  outputDir: '',
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: '2x',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realsr'),
  format: 'png',
};

export const initialVideoUpscale: VideoUpscaleJob = {
  kind: 'video-upscale',
  videoPath: '',
  outputPath: '',
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: '2x',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realsr'),
  format: 'mp4-h264',
};

export const initialBatchVideoToSequence: BatchVideoToSequenceJob = {
  kind: 'batch-video-to-sequence',
  sourceMode: 'files',
  videoPaths: [],
  scanRoot: '',
  recursive: true,
  outputMode: 'for-each',
  outputRoot: '',
  overrideFps: false,
  fps: 24,
  speed: 1,
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general-lite',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: 'off',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realesrgan'),
  format: 'png',
  prefix: 'frame',
  startNumber: 1,
};

export const initialBatchImageUpscale: BatchImageUpscaleJob = {
  kind: 'batch-image-upscale',
  sourceMode: 'files',
  imagePaths: [],
  scanRoot: '',
  recursive: true,
  outputMode: 'for-each',
  outputRoot: '',
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general-lite',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: '2x',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realsr'),
  format: 'png',
};

export const initialBatchVideoUpscale: BatchVideoUpscaleJob = {
  kind: 'batch-video-upscale',
  sourceMode: 'files',
  videoPaths: [],
  scanRoot: '',
  recursive: true,
  outputMode: 'for-each',
  outputRoot: '',
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general-lite',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: '2x',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realsr'),
  format: 'mp4-h264',
};

export const initialBatchSequenceToVideo: BatchSequenceToVideoJob = {
  kind: 'batch-sequence-to-video',
  sourceMode: 'folders',
  sequenceFolders: [],
  scanRoot: '',
  recursive: true,
  outputMode: 'for-each',
  outputRoot: '',
  fps: 24,
  speed: 1,
  quality: 100,
  backgroundRemove: false,
  backgroundRemoveModel: 'birefnet-general-lite',
  resolutionMode: 'source',
  customWidth: 1920,
  customHeight: 1080,
  upscaleMode: 'off',
  alphaMode: 'auto',
  upscalerConfig: createDefaultUpscalerConfig('realesrgan'),
  format: 'mp4-h264',
};
